# Generated by Django 4.2.2 on 2023-06-14 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ifrn", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="curso",
            name="descricao",
            field=models.TextField(),
        ),
    ]
